name: Build and test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Check if code is formatted
        run: v fmt -verify "${{ github.event.repository.name }}/"

      - name: Build
        run: v -prod "${{ github.event.repository.name }}/"

      - name: Run tests
        run: |
          cd ${{ github.event.repository.name }}
          v test "${{ github.event.repository.name }}/"
